### ISSUE TITLE
Navigation bar is not responsive for different viewports!

### ISSUE THREAD

**Issue by asmitsirohi** [PalisadoesFoundation/talawa-admin#220]
**Describe the bug**
Admin Navigation Bar is not responsive in different viewports.

**Expected behavior**
Admin Navigation Bar should be responsive at different viewports.

**Screenshots**
* Mobile View
 
![mobile_view](https://user-images.githubusercontent.com/63240102/148742066-700d4169-85d1-48e8-9cff-433f76a6d2c0.png)

* IPad View

![tablet_view](https://user-images.githubusercontent.com/63240102/148742159-77023e5d-2a6a-4732-8259-d4edf0c93288.png)

**Comment by Devesh21700Kumar** [comment]
> **Describe the bug** Admin Navigation Bar is not responsive in different viewports.
> 
> **Expected behavior** Admin Navigation Bar should be responsive at different viewports.
> 
> **Screenshots**
> 
> * Mobile View
> 
> ![mobile_view](https://user-images.githubusercontent.com/63240102/148742066-700d4169-85d1-48e8-9cff-433f76a6d2c0.png)
> 
> * IPad View
> 
> ![tablet_view](https://user-images.githubusercontent.com/63240102/148742159-77023e5d-2a6a-4732-8259-d4edf0c93288.png)

Hey @asmitsirohi This issue was referenced in #207 along with some other issues (which might have been fixed)
If u want then u can work on them as well

**Comment by asmitsirohi** [comment]
I thought the pull request for #207 was already merged and the issue for the navigation bar is not yet fixed.

I think it may be good to resolve all the UI-related issues in segments (in different issues). Because talawa-admin has serious UI-related issues, which may be troublesome to resolve in one go.

**Comment by palisadoes** [comment]
If we need to create a parent issue with children issues, what would they be? Would either of you be willing to create those?

**Comment by Devesh21700Kumar** [comment]
> If we need to create a parent issue with children issues, what would they be? Would either of you be willing to create those?

Yeah I'll do it.
I'll divide the #207 issue into different issues and remove the already fixed portions

**Comment by palisadoes** [comment]
After creating the parent issue:
- Please refer to each of the child issues in the body using bullets
- In each child issue refer to the parent in the body using bullets

You can find examples here:
- https://github.com/PalisadoesFoundation/talawa/issues/1023
- https://github.com/PalisadoesFoundation/talawa/issues/1013

**Comment by asmitsirohi** [comment]
@palisadoes I'm closing this issue because @Devesh21700Kumar mentioned this problem under #207.
